export const jobs = [
  {
    id: 1,
    title: 'Senior Product Designer',
    company: 'Northstar Labs',
    companyMark: 'N',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$142k – $168k',
    posted: '2 days ago',
    category: 'Design',
    featured: true,
    description: 'Shape the next generation of tools that help teams do their best work.',
    tags: ['Figma', 'Research', 'B2B'],
  },
  {
    id: 2,
    title: 'Frontend Engineer',
    company: 'Kindred Health',
    companyMark: 'K',
    location: 'Remote · United States',
    type: 'Full-time',
    salary: '$128k – $154k',
    posted: '4 days ago',
    category: 'Software Development',
    featured: true,
    description: 'Build calm, dependable digital experiences for a better healthcare system.',
    tags: ['React', 'TypeScript', 'GraphQL'],
  },
  {
    id: 3,
    title: 'Growth Marketing Manager',
    company: 'Pollen Studio',
    companyMark: 'P',
    location: 'Austin, TX',
    type: 'Full-time',
    salary: '$96k – $118k',
    posted: '1 week ago',
    category: 'Marketing',
    featured: true,
    description: 'Turn a loved product into a household name with a curious, sharp team.',
    tags: ['Growth', 'Content', 'Analytics'],
  },
  {
    id: 4,
    title: 'Data Analyst',
    company: 'Common Thread',
    companyMark: 'C',
    location: 'Chicago, IL',
    type: 'Full-time',
    salary: '$88k – $108k',
    posted: '1 week ago',
    category: 'Data Analytics',
    featured: true,
    description: 'Find the signal in complex data and make decisions easier for everyone.',
    tags: ['SQL', 'Python', 'Looker'],
  },
  {
    id: 5,
    title: 'Machine Learning Engineer',
    company: 'Helio Robotics',
    companyMark: 'H',
    location: 'Boston, MA',
    type: 'Full-time',
    salary: '$156k – $190k',
    posted: '2 weeks ago',
    category: 'AI & Machine Learning',
    featured: true,
    description: 'Bring embodied intelligence to the places where people live and work.',
    tags: ['Python', 'PyTorch', 'Robotics'],
  },
  {
    id: 6,
    title: 'Finance Operations Lead',
    company: 'Morrow & Co.',
    companyMark: 'M',
    location: 'Denver, CO',
    type: 'Hybrid',
    salary: '$104k – $126k',
    posted: '2 weeks ago',
    category: 'Finance',
    featured: true,
    description: 'Create the operating rhythm that lets an ambitious company move wisely.',
    tags: ['Strategy', 'FP&A', 'Operations'],
  },
  {
    id: 7,
    title: 'Content Strategist',
    company: 'Juniper Works',
    companyMark: 'J',
    location: 'Remote · United States',
    type: 'Contract',
    salary: '$72k – $94k',
    posted: '3 weeks ago',
    category: 'Marketing',
    description: 'Give a generous, growing brand a clear and compelling point of view.',
    tags: ['Editorial', 'Brand', 'SEO'],
  },
  {
    id: 8,
    title: 'Product Manager, Platform',
    company: 'Orbit House',
    companyMark: 'O',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$138k – $165k',
    posted: '3 weeks ago',
    category: 'Software Development',
    description: 'Lead a platform roadmap that quietly powers millions of daily moments.',
    tags: ['Roadmaps', 'APIs', 'Platforms'],
  },
  {
    id: 9,
    title: 'UX Researcher',
    company: 'Field Notes',
    companyMark: 'F',
    location: 'Portland, OR',
    type: 'Part-time',
    salary: '$78k – $102k',
    posted: '1 month ago',
    category: 'Design',
    description: 'Make space for better questions, deeper understanding, and useful answers.',
    tags: ['Qualitative', 'Strategy', 'UX'],
  },
];

export const categories = [
  { name: 'Software Development', count: '1,248 roles', icon: '⌘', accent: 'blue' },
  { name: 'Data Analytics', count: '624 roles', icon: '◌', accent: 'teal' },
  { name: 'AI & Machine Learning', count: '392 roles', icon: '✦', accent: 'indigo' },
  { name: 'Marketing', count: '518 roles', icon: '↗', accent: 'orange' },
  { name: 'Design', count: '406 roles', icon: '◈', accent: 'pink' },
  { name: 'Finance', count: '287 roles', icon: '$', accent: 'green' },
];